# Generated by Django 3.0.2 on 2020-01-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifanx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=20)),
                ('comment', models.TextField(max_length=250)),
                ('images', models.ImageField(blank=True, default='testimony/def.jpg', null=True, upload_to='testimony/')),
            ],
        ),
    ]
