# Generated by Django 3.0.2 on 2020-01-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sifanx', '0002_testimony'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimony',
            old_name='names',
            new_name='name',
        ),
    ]
