# Generated by Django 3.0.2 on 2020-01-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifanx', '0003_auto_20200113_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='name',
            field=models.TextField(max_length=20),
        ),
    ]
