# Generated by Django 3.0.2 on 2020-01-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifanx', '0004_auto_20200113_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='testmony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('comment', models.TextField(max_length=250)),
                ('images', models.ImageField(blank=True, default='testimony/def.jpg', null=True, upload_to='testimony/')),
            ],
        ),
        migrations.DeleteModel(
            name='testimony',
        ),
    ]
